language: rust

os:
    - osx

rust:
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm

before_install:
    - brew update
    - brew install nasm
    - brew install binutils

script:
    - make
